# **I. Norms**

## 1. Khái niệm

**Norm của vector** (Vector Norm) là một **đại lượng đo “độ dài” hoặc “kích thước” của vector** trong không gian vector.
Nói cách khác, norm cho ta biết một vector “lớn” đến mức nào, bất kể hướng của nó.

---

## 2. Ý nghĩa

* Giúp đo khoảng cách giữa hai điểm trong không gian
* Dùng để chuẩn hóa vector (tạo vector đơn vị)
* Ứng dụng nhiều trong Machine Learning, Deep Learning: regularization (L1, L2), tính loss, tối ưu

---

## 3. Ứng dụng trong ML/DL

* **Chuẩn hóa dữ liệu**: đưa vector về cùng độ dài để mô hình học ổn định
* **Regularization**:

  * L1: thúc đẩy mô hình học ra vector hệ số thưa (sparse)
  * L2: giảm độ lớn các hệ số, tránh overfitting
* **Tối ưu hóa**: đo độ lớn của gradient

## 4. Các loại Vector Norm

---

##### 1️⃣ **L1 Norm – Manhattan Norm**

$$
\|\mathbf{x}\|_1 = \sum_{i=1}^n |x_i|
$$

- Tính **tổng giá trị tuyệt đối** của các thành phần vector  
- Đo khoảng cách kiểu “đi dọc trục” (*Manhattan distance*)

**Ví dụ**:  

$$
\mathbf{x} = [3, -4, 5]
$$

$$
\|\mathbf{x}\|_1 = |3| + |-4| + |5| = 3 + 4 + 5 = 12
$$

---

##### 2️⃣ **L2 Norm – Euclidean Norm**

$$
\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}
$$

- Đo **khoảng cách Euclid** (đường thẳng từ gốc tới điểm)  
- Phổ biến nhất trong hình học và Machine Learning

**Ví dụ**:  

$$
\mathbf{x} = [3, -4]
$$

$$
\|\mathbf{x}\|_2 = \sqrt{3^2 + (-4)^2} = \sqrt{9 + 16} = 5
$$

---

##### 3️⃣ **Lp Norm – p-Norm (Tổng quát)**

$$
\|\mathbf{x}\|_p = \left( \sum_{i=1}^n |x_i|^p \right)^{\frac{1}{p}}, \quad p \ge 1
$$

- Tổng quát cho mọi \(p\)  
- L1, L2 là **trường hợp đặc biệt** của Lp

**Ví dụ**:  

$$
p = 3, \quad \mathbf{x} = [1, 2]
$$

$$
\|\mathbf{x}\|_3 = \left( |1|^3 + |2|^3 \right)^{\frac{1}{3}} = (1 + 8)^{\frac{1}{3}} \approx 2.08
$$

---

##### 4️⃣ **L∞ Norm – Max Norm**

$$
\|\mathbf{x}\|_\infty = \max_{i} |x_i|
$$

- Lấy **thành phần có giá trị tuyệt đối lớn nhất**  
- Dùng khi muốn đo “độ dài” dựa trên thành phần trội nhất

**Ví dụ**:  

$$
\mathbf{x} = [3, -4, 2]
$$

$$
\|\mathbf{x}\|_\infty = \max(3, 4, 2) = 4
$$


## 5. Code Demo

$L^2$ Norm

In [2]:
import numpy as np

In [3]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [4]:
(25**2 + 2**2 + 5**2)**0.5

25.573423705088842

In [5]:
np.linalg.norm(x)

25.573423705088842

$L^1$ Norm

In [6]:
x

array([25,  2,  5])

In [7]:
np.abs(25) + np.abs(2) + np.abs(5)

32

Squared $L^2$ Norm

In [8]:
x

array([25,  2,  5])

In [9]:
(25**2 + 2**2 + 5**2)

654

In [10]:
np.dot(x,x)

654

Max Norm

In [11]:
x

array([25,  2,  5])

In [12]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

# **II. Unit Vectors**

## 1. Định nghĩa

Vector đơn vị $u$ là một vector có độ dài (norm) bằng 1.

Công thức kiểm tra:

$$
\|\mathbf{u}\| = 1
$$

---

## 2. Cách chuẩn hóa vector thành Unit Vector

Cho một vector bất kỳ, unit vector cùng hướng được tính bằng:

$u$ = $x$ / $||x||$

Trong đó:
- $x$ là vector gốc

- $||x||$ là độ dài (norm) của vector gốc
---

## 3. Ví dụ

Cho vector:

$$
\mathbf{x} = [3, 4]
$$

Tính norm:

$$
\|\mathbf{x}\|_2 = \sqrt{3^2 + 4^2} = 5
$$

Vector đơn vị:

$$
\mathbf{u} = \frac{[3, 4]}{5} = \left[ \frac{3}{5}, \frac{4}{5} \right]
$$

---

## 4. Ứng dụng
- Xác định **hướng** trong không gian mà không bị ảnh hưởng bởi độ lớn
- Chuẩn hóa dữ liệu trong Machine Learning
- Tính vector pháp tuyến (normal vector) trong đồ họa máy tính
