# 🧮 Matrix (Ma Trận)

---

## 📌 Định nghĩa

$$
\text{Ma trận là một bảng chữ nhật gồm các phần tử (thường là số) sắp xếp theo hàng và cột.}
$$

Ký hiệu kích thước:  

$$
m \times n \quad (\text{m hàng, n cột})
$$

---

## 🧾 Ký hiệu tổng quát

$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}
$$

Trong đó:  

$$
a_{ij} \ \text{là phần tử ở hàng } i \ \text{và cột } j
$$

$$
1 \le i \le m, \quad 1 \le j \le n
$$

---

## 📏 Các loại ma trận thường gặp

**Ma trận vuông (Square Matrix)**:  

$$
m = n
$$

**Ma trận hàng (Row Matrix)**:  

$$
m = 1
$$

**Ma trận cột (Column Matrix)**:  

$$
n = 1
$$

**Ma trận không (Zero Matrix)**:  

$$
a_{ij} = 0 \quad \forall i, j
$$

**Ma trận đường chéo (Diagonal Matrix)**:  

$$
a_{ij} = 0 \quad \text{khi} \quad i \ne j
$$

**Ma trận đơn vị (Identity Matrix)**:  

$$
a_{ij} =
\begin{cases}
1, & i = j \\
0, & i \ne j
\end{cases}
$$

**Ma trận đối xứng (Symmetric Matrix)**:  

$$
A = A^T
$$

---

## 🔄 Các phép toán cơ bản

**1️⃣ Cộng ma trận**  

$$
C = A + B, \quad c_{ij} = a_{ij} + b_{ij}
$$

**2️⃣ Nhân ma trận với số vô hướng**  

$$
kA = [k \cdot a_{ij}]
$$

**3️⃣ Nhân ma trận**  

$$
\text{Nếu} \quad A_{m \times n}, \ B_{n \times p} \quad \text{thì}
$$

$$
C = AB, \quad c_{ij} = \sum_{k=1}^n a_{ik} b_{kj}
$$

**4️⃣ Chuyển vị ma trận**  

$$
A^T: \quad \text{đổi hàng thành cột và cột thành hàng}
$$

---

## 💡 Ví dụ

Ma trận \(A\):  

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

Chuyển vị:  

$$
A^T =
\begin{bmatrix}
1 & 3 \\
2 & 4
\end{bmatrix}
$$

Nhân với vector:  

$$
\mathbf{x} =
\begin{bmatrix}
5 \\
6
\end{bmatrix}
$$

$$
A \mathbf{x} =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\begin{bmatrix}
5 \\
6
\end{bmatrix}
=
\begin{bmatrix}
17 \\
39
\end{bmatrix}
$$


# Numpy

In [1]:
import numpy as np

In [2]:
x = np.array([[25,2] , [5,26], [3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
x.shape

(3, 2)

In [4]:
x.size

6

In [ ]:
x[:,0] # Get the first column

array([25,  5,  3])

In [ ]:
x[1,:] # Get the second row

array([ 5, 26])

In [7]:
x[0:2, 0:2] # Get the first two rows and first two columns

array([[25,  2],
       [ 5, 26]])

# PyTorch

In [ ]:
import torch

In [ ]:
x_pt = torch.tensor([[25,2] , [5,26], [3,7]])
x_pt

In [ ]:
x_pt.shape

In [ ]:
x_pt[1,:] # Get the second row

# TensorFlow

In [ ]:
import tensorflow as tf

In [ ]:
x_tf = tf.Variable([[25,2] , [5,26], [3,7]])
x_tf

In [ ]:
tf.rank(x_tf)  # Get the rank of the tensor

In [ ]:
tf.shape(x_tf)  # Get the shape of the tensor

In [ ]:
x_tf[1,:]  # Get the second row